[package]
name = "cmdipass"
version = "0.2.0"
authors = ["Justin Fitzsimmons <justinf@nulogy.com>"]

[dependencies]
docopt = "0.8"
hyper = "0.10"
rust-crypto = "0.2"
base64 = "0.3"
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.3"
env_logger = "0.3"
